-- ============================================
-- Migration: Real org structure and approval routes
-- ユニフォーム・SP部 組織構造、従業員、書類種別、承認ルート
-- Generated by gen_migration.py
-- ============================================

BEGIN;

-- ============================================
-- 1. Clean existing data (dependency order)
-- ============================================

DELETE FROM audit_logs;
DELETE FROM notifications;
DELETE FROM application_comments;
DELETE FROM application_attachments;
DELETE FROM approval_records;
DELETE FROM applications;
DELETE FROM proxy_settings;
DELETE FROM approval_route_steps;
DELETE FROM approval_route_templates;
DELETE FROM form_templates;
DELETE FROM document_types;
DELETE FROM employee_assignments;
DELETE FROM employees;
DELETE FROM departments;

-- ============================================
-- 2. Add new positions (keep existing 9)
-- ============================================

INSERT INTO positions (name, code, rank)
VALUES ('統括部長', 'TOKATSU_BUCHO', 85)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, rank = EXCLUDED.rank;
INSERT INTO positions (name, code, rank)
VALUES ('MD', 'MD', 65)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, rank = EXCLUDED.rank;
INSERT INTO positions (name, code, rank)
VALUES ('パタンナー', 'PATTERNMAKER', 30)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, rank = EXCLUDED.rank;

-- ============================================
-- 3. Insert departments (new org structure)
-- ============================================

INSERT INTO departments (name, code, level, sort_order)
VALUES ('ユニフォーム・SP部', 'USP', 0, 1);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('営業部', 'USP-SALES', (SELECT id FROM departments WHERE code = 'USP'), 1, 1);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('企画生産部', 'USP-PROD', (SELECT id FROM departments WHERE code = 'USP'), 1, 2);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('レンタルチーム', 'USP-SALES-RT', (SELECT id FROM departments WHERE code = 'USP-SALES'), 2, 1);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('営業第1課', 'USP-SALES-1', (SELECT id FROM departments WHERE code = 'USP-SALES'), 2, 2);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('営業第2課', 'USP-SALES-2', (SELECT id FROM departments WHERE code = 'USP-SALES'), 2, 3);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('営業第3課', 'USP-SALES-3', (SELECT id FROM departments WHERE code = 'USP-SALES'), 2, 4);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('営業第4課', 'USP-SALES-4', (SELECT id FROM departments WHERE code = 'USP-SALES'), 2, 5);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('営業第5課', 'USP-SALES-5', (SELECT id FROM departments WHERE code = 'USP-SALES'), 2, 6);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('企画課', 'USP-PROD-PLAN', (SELECT id FROM departments WHERE code = 'USP-PROD'), 2, 1);

INSERT INTO departments (name, code, parent_id, level, sort_order)
VALUES ('生産課', 'USP-PROD-MFG', (SELECT id FROM departments WHERE code = 'USP-PROD'), 2, 2);

-- ============================================
-- 4. Insert employees
-- ============================================

INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-001', '黒木信吾', 's-kuroki@tsukamoto.co.jp', true);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-002', '光田宏渡', 'h-mitsuta@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-003', '安井計志', 'k-yasui@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-004', '北村京一郎', 'k-kitamura@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-005', '久保岳', 'i-kubo@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-006', '石野未貴', 'm-ishino@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-007', '山下素直', 'n-yamashita@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-008', '紫竹洋子', 'y-shichiku@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-009', '奥田祥覚', 'y-okuda@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-010', '稲葉暢', 'n-inaba@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-011', '佐藤貴丈', 'ta-sato@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-012', '滝澤亮人', 'r-takizawa@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-013', '昼間紀子', 'n-hiruma@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-014', '原直樹', 'y-hara@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-015', '尾沢由香', 'y-ozawa@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-016', '関野太郎', 't-sekino@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-017', '上田雅輝乃', 'y-ueda@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-018', '越智泰', 'y-ochi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-019', '養老秀一', 'h-yourou@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-020', '松岡孝浩', 't-matsuoka@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-021', '柳正岐', 's-yanagi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-022', '植村嘉一', 'k-uemura@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-023', '森口陽子', 'm-moriguchi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-024', '高科将嗣', 'y-takashina@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-025', '森脇涼夢', 's-moriwaki@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-026', '白畑武乃', 'a-shirahata@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-027', '加藤直直', 'na-kato@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-028', '有路亜美', 'ariji@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-029', '中島海香', 'm-nakajima@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-030', '五十嵐歩夢', 'a-ikarashi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-031', '杉山日向', 'h-sugiyama@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-032', '永岡蒼乃真', 'n-nagaoka@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-033', '松本隆平', 'r-matsumoto@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-034', '斉藤彰', 'a-saito@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-035', '福島岳崎', 'f-fukushima@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-036', '高橋裕之', 'hi-takahashi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-037', '茨木朝日香', 'a-ibaragi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-038', '大森碧', 'h-omori@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-039', '岩崎泰治', 'y-iwasaki@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-040', '野口幸大', 'k-noguchi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-041', '栁内隆佑', 'r-yanai@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-042', '中橋順子', 'j-nakahashi@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-043', '菱沼嫣離子', 'y-hishinuma@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-044', '水戸由美子', 'y-mito@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-045', '加藤義男', 'y-kato@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-046', '石井好美', 'y-ishii@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-047', '佐々本満', 'mi-sasamoto@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-048', '斎藤なり美', 'n-saito@tsukamoto.co.jp', false);
INSERT INTO employees (employee_number, name, email, is_admin)
VALUES ('EMP-049', '中山伸一', 's-nakayama@tsukamoto.co.jp', false);

-- ============================================
-- 4b. Insert primary employee assignments
-- ============================================

INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 's-kuroki@tsukamoto.co.jp' AND d.code = 'USP' AND p.code = 'JIGYOBUCHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'h-mitsuta@tsukamoto.co.jp' AND d.code = 'USP-SALES' AND p.code = 'BUCHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'k-yasui@tsukamoto.co.jp' AND d.code = 'USP-SALES' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'k-kitamura@tsukamoto.co.jp' AND d.code = 'USP-SALES' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'i-kubo@tsukamoto.co.jp' AND d.code = 'USP-SALES' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'm-ishino@tsukamoto.co.jp' AND d.code = 'USP-SALES-RT' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'n-yamashita@tsukamoto.co.jp' AND d.code = 'USP-SALES-RT' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-shichiku@tsukamoto.co.jp' AND d.code = 'USP-SALES-RT' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-okuda@tsukamoto.co.jp' AND d.code = 'USP-SALES-1' AND p.code = 'KACHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'n-inaba@tsukamoto.co.jp' AND d.code = 'USP-SALES-1' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'ta-sato@tsukamoto.co.jp' AND d.code = 'USP-SALES-1' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'r-takizawa@tsukamoto.co.jp' AND d.code = 'USP-SALES-1' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'n-hiruma@tsukamoto.co.jp' AND d.code = 'USP-SALES-1' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-hara@tsukamoto.co.jp' AND d.code = 'USP-SALES-2' AND p.code = 'KACHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-ozawa@tsukamoto.co.jp' AND d.code = 'USP-SALES-2' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 't-sekino@tsukamoto.co.jp' AND d.code = 'USP-SALES-2' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-ueda@tsukamoto.co.jp' AND d.code = 'USP-SALES-2' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-ochi@tsukamoto.co.jp' AND d.code = 'USP-SALES-3' AND p.code = 'KACHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'h-yourou@tsukamoto.co.jp' AND d.code = 'USP-SALES-3' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 't-matsuoka@tsukamoto.co.jp' AND d.code = 'USP-SALES-3' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 's-yanagi@tsukamoto.co.jp' AND d.code = 'USP-SALES-3' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'k-uemura@tsukamoto.co.jp' AND d.code = 'USP-SALES-4' AND p.code = 'KACHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'm-moriguchi@tsukamoto.co.jp' AND d.code = 'USP-SALES-4' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-takashina@tsukamoto.co.jp' AND d.code = 'USP-SALES-4' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 's-moriwaki@tsukamoto.co.jp' AND d.code = 'USP-SALES-4' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'a-shirahata@tsukamoto.co.jp' AND d.code = 'USP-SALES-4' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'na-kato@tsukamoto.co.jp' AND d.code = 'USP-SALES-5' AND p.code = 'KACHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'ariji@tsukamoto.co.jp' AND d.code = 'USP-SALES-5' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'm-nakajima@tsukamoto.co.jp' AND d.code = 'USP-SALES-5' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'a-ikarashi@tsukamoto.co.jp' AND d.code = 'USP-SALES-5' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'h-sugiyama@tsukamoto.co.jp' AND d.code = 'USP-SALES-5' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'n-nagaoka@tsukamoto.co.jp' AND d.code = 'USP-SALES-5' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'r-matsumoto@tsukamoto.co.jp' AND d.code = 'USP-SALES-5' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'a-saito@tsukamoto.co.jp' AND d.code = 'USP-PROD' AND p.code = 'BUCHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'f-fukushima@tsukamoto.co.jp' AND d.code = 'USP-PROD' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'hi-takahashi@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'KACHO';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'a-ibaragi@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'h-omori@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-iwasaki@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'k-noguchi@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'r-yanai@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'j-nakahashi@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-hishinuma@tsukamoto.co.jp' AND d.code = 'USP-PROD-PLAN' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-mito@tsukamoto.co.jp' AND d.code = 'USP-PROD-MFG' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-kato@tsukamoto.co.jp' AND d.code = 'USP-PROD-MFG' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'y-ishii@tsukamoto.co.jp' AND d.code = 'USP-PROD-MFG' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'mi-sasamoto@tsukamoto.co.jp' AND d.code = 'USP-PROD-MFG' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 'n-saito@tsukamoto.co.jp' AND d.code = 'USP-PROD-MFG' AND p.code = 'IPPAN';
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, true, true
FROM employees e, departments d, positions p
WHERE e.email = 's-nakayama@tsukamoto.co.jp' AND d.code = 'USP-PROD-MFG' AND p.code = 'IPPAN';

-- ============================================
-- 4c. Insert secondary employee assignments
-- ============================================

-- h-mitsuta: secondary as KACHO in USP-SALES-RT
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, false, true
FROM employees e, departments d, positions p
WHERE e.email = 'h-mitsuta@tsukamoto.co.jp' AND d.code = 'USP-SALES-RT' AND p.code = 'KACHO';

-- a-saito: secondary as KACHO in USP-PROD-MFG
INSERT INTO employee_assignments (employee_id, department_id, position_id, is_primary, is_active)
SELECT e.id, d.id, p.id, false, true
FROM employees e, departments d, positions p
WHERE e.email = 'a-saito@tsukamoto.co.jp' AND d.code = 'USP-PROD-MFG' AND p.code = 'KACHO';

-- ============================================
-- 5. Insert document types
-- ============================================

INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T01', 'デザイン企画依頼書', '業務依頼', 'Palette', 1);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T02a', '見積書（1000万未満）', '請求', 'FileText', 2);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T02b', '見積書（1000～3000万）', '請求', 'FileText', 3);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T02c', '見積書（3000万以上）', '請求', 'FileText', 4);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T03', '生地手配依頼書', '業務依頼', 'Scissors', 5);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T04', '仕様変更依頼書', '業務依頼', 'Settings', 6);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T04b', '仕様修正依頼書', '業務依頼', 'Settings', 7);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T05', 'コンペ結果報告書', '社内申請', 'Trophy', 8);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T06', 'クレーム報告書', '社内申請', 'AlertTriangle', 9);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T08a', '企画外注向け注文書（50万未満）', '業務依頼', 'ShoppingCart', 10);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T08b', '企画外注向け注文書（50万以上100万未満）', '業務依頼', 'ShoppingCart', 11);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T08c', '企画外注向け注文書（100万以上）', '業務依頼', 'ShoppingCart', 12);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T09a', 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万未満）', '業務依頼', 'Ruler', 13);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T09b', 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万以上100万未満）', '業務依頼', 'Ruler', 14);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T09c', 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（100万以上）', '業務依頼', 'Ruler', 15);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T10a', '生地発注書（1000万未満）', '業務依頼', 'Package', 16);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T10b', '生地発注書（1000万以上）', '業務依頼', 'Package', 17);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T11a', '付属発注書（1000万未満）', '業務依頼', 'Package', 18);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T11b', '付属発注書（1000万以上）', '業務依頼', 'Package', 19);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T12a', '加工指図書（1000万未満）', '業務依頼', 'Factory', 20);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T12b', '加工指図書（1000～3000万）', '業務依頼', 'Factory', 21);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T12c', '加工指図書（3000万以上）', '業務依頼', 'Factory', 22);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T13', '請求書', '請求', 'Receipt', 23);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T14', '採寸申請書', '社内申請', 'Ruler', 24);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T15', '海外出張申請書', '社内申請', 'Plane', 25);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T16', '海外出張報告書', '社内申請', 'FileCheck', 26);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T17', '国内出張報告書', '社内申請', 'Car', 27);
INSERT INTO document_types (code, name, category, icon, sort_order)
VALUES ('T18', '有給休暇/半休申請書', '社内申請', 'Calendar', 28);

-- ============================================
-- 6. Insert form templates
-- ============================================

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "request_content", "type": "textarea", "label": "依頼内容", "required": true, "rows": 6}, {"id": "deadline", "type": "date", "label": "納期", "required": true}, {"id": "budget", "type": "currency", "label": "予算", "required": false}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "依頼詳細", "fields": ["request_content", "deadline", "budget"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T01';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "estimate_items", "type": "table", "label": "見積明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "30%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "10%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 50}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(estimate_items.subtotal)"}, {"id": "valid_until", "type": "date", "label": "有効期限", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "見積明細", "fields": ["estimate_items", "total_amount"]}, {"title": "条件", "fields": ["valid_until", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T02a';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "estimate_items", "type": "table", "label": "見積明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "30%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "10%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 50}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(estimate_items.subtotal)"}, {"id": "valid_until", "type": "date", "label": "有効期限", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "見積明細", "fields": ["estimate_items", "total_amount"]}, {"title": "条件", "fields": ["valid_until", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T02b';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "estimate_items", "type": "table", "label": "見積明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "30%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "10%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 50}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(estimate_items.subtotal)"}, {"id": "valid_until", "type": "date", "label": "有効期限", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "見積明細", "fields": ["estimate_items", "total_amount"]}, {"title": "条件", "fields": ["valid_until", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T02c';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "fabric_items", "type": "table", "label": "生地情報", "columns": [{"id": "fabric_name", "type": "text", "label": "生地名", "width": "25%"}, {"id": "color", "type": "text", "label": "色", "width": "15%"}, {"id": "width", "type": "text", "label": "巾", "width": "10%"}, {"id": "quantity", "type": "number", "label": "数量(m)", "width": "15%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(fabric_items.subtotal)"}, {"id": "desired_delivery", "type": "date", "label": "希望納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "生地情報", "fields": ["fabric_items", "total_amount"]}, {"title": "納期・備考", "fields": ["desired_delivery", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T03';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "change_content", "type": "textarea", "label": "変更内容", "required": true, "rows": 6}, {"id": "change_reason", "type": "textarea", "label": "変更理由", "required": true, "rows": 4}, {"id": "impact_scope", "type": "textarea", "label": "影響範囲", "required": true, "rows": 4}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name"]}, {"title": "変更詳細", "fields": ["change_content", "change_reason", "impact_scope"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T04';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "correction_content", "type": "textarea", "label": "修正内容", "required": true, "rows": 6}, {"id": "correction_reason", "type": "textarea", "label": "修正理由", "required": true, "rows": 4}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name"]}, {"title": "修正詳細", "fields": ["correction_content", "correction_reason"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T04b';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "competition_result", "type": "select", "label": "コンペ結果", "required": true, "options": [{"value": "won", "label": "受注"}, {"value": "lost", "label": "失注"}, {"value": "pending", "label": "保留"}]}, {"id": "order_amount", "type": "currency", "label": "受注金額", "required": false}, {"id": "result_detail", "type": "textarea", "label": "結果詳細", "required": true, "rows": 6}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "コンペ結果", "fields": ["competition_result", "order_amount", "result_detail"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T05';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "occurrence_date", "type": "date", "label": "発生日", "required": true}, {"id": "claim_content", "type": "textarea", "label": "クレーム内容", "required": true, "rows": 6}, {"id": "cause", "type": "textarea", "label": "原因", "required": true, "rows": 4}, {"id": "countermeasure", "type": "textarea", "label": "対策", "required": true, "rows": 4}, {"id": "damage_amount", "type": "currency", "label": "被害金額", "required": false}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name", "occurrence_date"]}, {"title": "クレーム詳細", "fields": ["claim_content", "cause", "countermeasure"]}, {"title": "影響・備考", "fields": ["damage_amount", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T06';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "vendor_name", "type": "text", "label": "外注先名", "required": true}, {"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "order_date", "type": "date", "label": "発注日", "required": true}, {"id": "delivery_date", "type": "date", "label": "納期", "required": true}, {"id": "item_spec", "type": "text", "label": "品名・仕様", "required": true}, {"id": "quantity", "type": "number", "label": "数量", "required": true}, {"id": "unit_price", "type": "currency", "label": "単価", "required": true}, {"id": "amount", "type": "formula", "label": "金額", "formula": "quantity * unit_price"}, {"id": "detail_table", "type": "table", "label": "明細テーブル", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "25%"}, {"id": "qty", "type": "number", "label": "数量", "width": "10%"}, {"id": "price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "line_amount", "type": "formula", "label": "金額", "formula": "qty * price", "width": "15%"}], "minRows": 1, "maxRows": 20, "allowExcelPaste": true}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(detail_table.line_amount)"}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}, {"id": "delivery_location", "type": "text", "label": "納品場所", "required": false}], "layout": {"type": "sections", "sections": [{"title": "発注先情報", "fields": ["vendor_name", "project_name"]}, {"title": "発注条件", "fields": ["order_date", "delivery_date", "item_spec", "quantity", "unit_price", "amount"]}, {"title": "明細", "fields": ["detail_table", "total_amount"]}, {"title": "備考・納品", "fields": ["remarks", "delivery_location"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T08a';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "vendor_name", "type": "text", "label": "外注先名", "required": true}, {"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "order_date", "type": "date", "label": "発注日", "required": true}, {"id": "delivery_date", "type": "date", "label": "納期", "required": true}, {"id": "item_spec", "type": "text", "label": "品名・仕様", "required": true}, {"id": "quantity", "type": "number", "label": "数量", "required": true}, {"id": "unit_price", "type": "currency", "label": "単価", "required": true}, {"id": "amount", "type": "formula", "label": "金額", "formula": "quantity * unit_price"}, {"id": "detail_table", "type": "table", "label": "明細テーブル", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "25%"}, {"id": "qty", "type": "number", "label": "数量", "width": "10%"}, {"id": "price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "line_amount", "type": "formula", "label": "金額", "formula": "qty * price", "width": "15%"}], "minRows": 1, "maxRows": 20, "allowExcelPaste": true}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(detail_table.line_amount)"}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}, {"id": "delivery_location", "type": "text", "label": "納品場所", "required": false}], "layout": {"type": "sections", "sections": [{"title": "発注先情報", "fields": ["vendor_name", "project_name"]}, {"title": "発注条件", "fields": ["order_date", "delivery_date", "item_spec", "quantity", "unit_price", "amount"]}, {"title": "明細", "fields": ["detail_table", "total_amount"]}, {"title": "備考・納品", "fields": ["remarks", "delivery_location"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T08b';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "vendor_name", "type": "text", "label": "外注先名", "required": true}, {"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "order_date", "type": "date", "label": "発注日", "required": true}, {"id": "delivery_date", "type": "date", "label": "納期", "required": true}, {"id": "item_spec", "type": "text", "label": "品名・仕様", "required": true}, {"id": "quantity", "type": "number", "label": "数量", "required": true}, {"id": "unit_price", "type": "currency", "label": "単価", "required": true}, {"id": "amount", "type": "formula", "label": "金額", "formula": "quantity * unit_price"}, {"id": "detail_table", "type": "table", "label": "明細テーブル", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "25%"}, {"id": "qty", "type": "number", "label": "数量", "width": "10%"}, {"id": "price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "line_amount", "type": "formula", "label": "金額", "formula": "qty * price", "width": "15%"}], "minRows": 1, "maxRows": 20, "allowExcelPaste": true}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(detail_table.line_amount)"}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}, {"id": "delivery_location", "type": "text", "label": "納品場所", "required": false}], "layout": {"type": "sections", "sections": [{"title": "発注先情報", "fields": ["vendor_name", "project_name"]}, {"title": "発注条件", "fields": ["order_date", "delivery_date", "item_spec", "quantity", "unit_price", "amount"]}, {"title": "明細", "fields": ["detail_table", "total_amount"]}, {"title": "備考・納品", "fields": ["remarks", "delivery_location"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T08c';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "pattern_spec", "type": "textarea", "label": "パターン仕様", "required": true, "rows": 6}, {"id": "size_table", "type": "table", "label": "サイズ展開", "columns": [{"id": "size", "type": "text", "label": "サイズ", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "20%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "20%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "20%"}], "minRows": 1, "maxRows": 20}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(size_table.subtotal)"}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name"]}, {"title": "パターン仕様", "fields": ["pattern_spec", "size_table", "total_amount"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T09a';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "pattern_spec", "type": "textarea", "label": "パターン仕様", "required": true, "rows": 6}, {"id": "size_table", "type": "table", "label": "サイズ展開", "columns": [{"id": "size", "type": "text", "label": "サイズ", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "20%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "20%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "20%"}], "minRows": 1, "maxRows": 20}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(size_table.subtotal)"}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name"]}, {"title": "パターン仕様", "fields": ["pattern_spec", "size_table", "total_amount"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T09b';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "pattern_spec", "type": "textarea", "label": "パターン仕様", "required": true, "rows": 6}, {"id": "size_table", "type": "table", "label": "サイズ展開", "columns": [{"id": "size", "type": "text", "label": "サイズ", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "20%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "20%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "20%"}], "minRows": 1, "maxRows": 20}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(size_table.subtotal)"}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name"]}, {"title": "パターン仕様", "fields": ["pattern_spec", "size_table", "total_amount"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T09c';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "vendor_name", "type": "text", "label": "発注先", "required": true}, {"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "fabric_items", "type": "table", "label": "生地明細", "columns": [{"id": "fabric_name", "type": "text", "label": "生地名", "width": "20%"}, {"id": "color", "type": "text", "label": "色", "width": "15%"}, {"id": "quantity", "type": "number", "label": "数量(m)", "width": "15%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(fabric_items.subtotal)"}, {"id": "delivery_date", "type": "date", "label": "希望納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "発注先情報", "fields": ["vendor_name", "project_name"]}, {"title": "生地明細", "fields": ["fabric_items", "total_amount"]}, {"title": "納期・備考", "fields": ["delivery_date", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T10a';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "vendor_name", "type": "text", "label": "発注先", "required": true}, {"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "fabric_items", "type": "table", "label": "生地明細", "columns": [{"id": "fabric_name", "type": "text", "label": "生地名", "width": "20%"}, {"id": "color", "type": "text", "label": "色", "width": "15%"}, {"id": "quantity", "type": "number", "label": "数量(m)", "width": "15%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(fabric_items.subtotal)"}, {"id": "delivery_date", "type": "date", "label": "希望納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "発注先情報", "fields": ["vendor_name", "project_name"]}, {"title": "生地明細", "fields": ["fabric_items", "total_amount"]}, {"title": "納期・備考", "fields": ["delivery_date", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T10b';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "vendor_name", "type": "text", "label": "発注先", "required": true}, {"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "accessory_items", "type": "table", "label": "付属明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "15%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(accessory_items.subtotal)"}, {"id": "delivery_date", "type": "date", "label": "希望納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "発注先情報", "fields": ["vendor_name", "project_name"]}, {"title": "付属明細", "fields": ["accessory_items", "total_amount"]}, {"title": "納期・備考", "fields": ["delivery_date", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T11a';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "vendor_name", "type": "text", "label": "発注先", "required": true}, {"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "accessory_items", "type": "table", "label": "付属明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "20%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "15%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(accessory_items.subtotal)"}, {"id": "delivery_date", "type": "date", "label": "希望納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "発注先情報", "fields": ["vendor_name", "project_name"]}, {"title": "付属明細", "fields": ["accessory_items", "total_amount"]}, {"title": "納期・備考", "fields": ["delivery_date", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T11b';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "processing_items", "type": "table", "label": "加工明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "process_type", "type": "text", "label": "加工種別", "width": "15%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "15%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "10%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(processing_items.subtotal)"}, {"id": "delivery_date", "type": "date", "label": "納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "加工明細", "fields": ["processing_items", "total_amount"]}, {"title": "納期・備考", "fields": ["delivery_date", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T12a';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "processing_items", "type": "table", "label": "加工明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "process_type", "type": "text", "label": "加工種別", "width": "15%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "15%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "10%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(processing_items.subtotal)"}, {"id": "delivery_date", "type": "date", "label": "納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "加工明細", "fields": ["processing_items", "total_amount"]}, {"title": "納期・備考", "fields": ["delivery_date", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T12b';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "customer_name", "type": "text", "label": "顧客名", "required": true}, {"id": "processing_items", "type": "table", "label": "加工明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "20%"}, {"id": "process_type", "type": "text", "label": "加工種別", "width": "15%"}, {"id": "spec", "type": "text", "label": "仕様", "width": "15%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "10%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "total_amount", "type": "formula", "label": "合計金額", "formula": "SUM(processing_items.subtotal)"}, {"id": "delivery_date", "type": "date", "label": "納期", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "基本情報", "fields": ["project_name", "customer_name"]}, {"title": "加工明細", "fields": ["processing_items", "total_amount"]}, {"title": "納期・備考", "fields": ["delivery_date", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T12c';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "billing_to", "type": "text", "label": "請求先", "required": true}, {"id": "subject", "type": "text", "label": "件名", "required": true}, {"id": "billing_items", "type": "table", "label": "請求明細", "columns": [{"id": "item_name", "type": "text", "label": "品名", "width": "25%"}, {"id": "quantity", "type": "number", "label": "数量", "width": "10%"}, {"id": "unit_price", "type": "currency", "label": "単価", "width": "15%"}, {"id": "subtotal", "type": "formula", "label": "金額", "formula": "quantity * unit_price", "width": "15%"}], "minRows": 1, "maxRows": 30}, {"id": "subtotal_amount", "type": "formula", "label": "小計", "formula": "SUM(billing_items.subtotal)"}, {"id": "tax_amount", "type": "formula", "label": "消費税（10%）", "formula": "subtotal_amount * 0.1"}, {"id": "total_amount", "type": "formula", "label": "合計金額（税込）", "formula": "subtotal_amount + tax_amount"}, {"id": "payment_deadline", "type": "date", "label": "支払期限", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "請求先情報", "fields": ["billing_to", "subject"]}, {"title": "請求明細", "fields": ["billing_items", "subtotal_amount", "tax_amount", "total_amount"]}, {"title": "支払条件", "fields": ["payment_deadline", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T13';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "project_name", "type": "text", "label": "案件名", "required": true}, {"id": "visit_location", "type": "text", "label": "訪問先", "required": true}, {"id": "visit_date", "type": "date", "label": "訪問日", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "採寸情報", "fields": ["project_name", "visit_location", "visit_date"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T14';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "destination", "type": "text", "label": "出張先", "required": true}, {"id": "start_date", "type": "date", "label": "出張開始日", "required": true}, {"id": "end_date", "type": "date", "label": "出張終了日", "required": true}, {"id": "purpose", "type": "textarea", "label": "目的", "required": true, "rows": 4}, {"id": "estimated_cost", "type": "currency", "label": "概算費用", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "出張情報", "fields": ["destination", "start_date", "end_date"]}, {"title": "目的・費用", "fields": ["purpose", "estimated_cost"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T15';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "destination", "type": "text", "label": "出張先", "required": true}, {"id": "start_date", "type": "date", "label": "出張開始日", "required": true}, {"id": "end_date", "type": "date", "label": "出張終了日", "required": true}, {"id": "report_content", "type": "textarea", "label": "報告内容", "required": true, "rows": 8}, {"id": "actual_cost", "type": "currency", "label": "実費用", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "出張情報", "fields": ["destination", "start_date", "end_date"]}, {"title": "報告", "fields": ["report_content", "actual_cost"]}, {"title": "備考", "fields": ["remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T16';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "destination", "type": "text", "label": "出張先", "required": true}, {"id": "start_date", "type": "date", "label": "出張開始日", "required": true}, {"id": "end_date", "type": "date", "label": "出張終了日", "required": true}, {"id": "purpose", "type": "textarea", "label": "目的", "required": true, "rows": 4}, {"id": "report_content", "type": "textarea", "label": "報告内容", "required": true, "rows": 6}, {"id": "transportation_cost", "type": "currency", "label": "交通費", "required": true}, {"id": "remarks", "type": "textarea", "label": "備考", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "出張情報", "fields": ["destination", "start_date", "end_date"]}, {"title": "報告", "fields": ["purpose", "report_content"]}, {"title": "費用・備考", "fields": ["transportation_cost", "remarks"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T17';

INSERT INTO form_templates (document_type_id, version, is_current, schema)
SELECT dt.id, 1, true, '{"version": "1.0", "fields": [{"id": "leave_type", "type": "select", "label": "休暇種別", "required": true, "options": [{"value": "paid_leave", "label": "有給休暇"}, {"value": "half_day_am", "label": "半休（午前）"}, {"value": "half_day_pm", "label": "半休（午後）"}]}, {"id": "start_date", "type": "date", "label": "開始日", "required": true}, {"id": "end_date", "type": "date", "label": "終了日", "required": true}, {"id": "reason", "type": "textarea", "label": "事由", "required": false, "rows": 3}], "layout": {"type": "sections", "sections": [{"title": "休暇情報", "fields": ["leave_type", "start_date", "end_date"]}, {"title": "事由", "fields": ["reason"]}]}}'::jsonb
FROM document_types dt WHERE dt.code = 'T18';

-- ============================================
-- 7. Insert approval route templates and steps
-- ============================================

-- Route: デザイン企画依頼書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, 'デザイン企画依頼書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T01';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T01' AND art.name = 'デザイン企画依頼書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T01' AND art.name = 'デザイン企画依頼書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T01' AND art.name = 'デザイン企画依頼書 承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 4, '生産担当', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T01' AND art.name = 'デザイン企画依頼書 承認ルート' AND e.email = 'y-mito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 5, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T01' AND art.name = 'デザイン企画依頼書 承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 6, '企画MD', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T01' AND art.name = 'デザイン企画依頼書 承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 7, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T01' AND art.name = 'デザイン企画依頼書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 見積書（1000万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '見積書（1000万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T02a';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T02a' AND art.name = '見積書（1000万未満）承認ルート' AND p.code = 'KACHO';

-- Route: 見積書（1000～3000万）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '見積書（1000～3000万）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T02b';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T02b' AND art.name = '見積書（1000～3000万）承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T02b' AND art.name = '見積書（1000～3000万）承認ルート' AND p.code = 'BUCHO';

-- Route: 見積書（3000万以上）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '見積書（3000万以上）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T02c';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T02c' AND art.name = '見積書（3000万以上）承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T02c' AND art.name = '見積書（3000万以上）承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T02c' AND art.name = '見積書（3000万以上）承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 生地手配依頼書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '生地手配依頼書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T03';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T03' AND art.name = '生地手配依頼書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T03' AND art.name = '生地手配依頼書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T03' AND art.name = '生地手配依頼書 承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 4, '生産担当', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T03' AND art.name = '生地手配依頼書 承認ルート' AND e.email = 'y-mito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 5, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T03' AND art.name = '生地手配依頼書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 仕様変更依頼書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '仕様変更依頼書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T04';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T04' AND art.name = '仕様変更依頼書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T04' AND art.name = '仕様変更依頼書 承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '生産担当', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T04' AND art.name = '仕様変更依頼書 承認ルート' AND e.email = 'y-mito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 4, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T04' AND art.name = '仕様変更依頼書 承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 5, '担当パタンナー', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T04' AND art.name = '仕様変更依頼書 承認ルート' AND e.email = 'h-omori@tsukamoto.co.jp';

-- Route: 仕様修正依頼書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '仕様修正依頼書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T04b';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T04b' AND art.name = '仕様修正依頼書 承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T04b' AND art.name = '仕様修正依頼書 承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '担当パタンナー', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T04b' AND art.name = '仕様修正依頼書 承認ルート' AND e.email = 'h-omori@tsukamoto.co.jp';

-- Route: コンペ結果報告書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, 'コンペ結果報告書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T05';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T05' AND art.name = 'コンペ結果報告書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T05' AND art.name = 'コンペ結果報告書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '担当MD', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T05' AND art.name = 'コンペ結果報告書 承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 4, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T05' AND art.name = 'コンペ結果報告書 承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 5, '生産担当', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T05' AND art.name = 'コンペ結果報告書 承認ルート' AND e.email = 'y-mito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 6, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T05' AND art.name = 'コンペ結果報告書 承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 7, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T05' AND art.name = 'コンペ結果報告書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: クレーム報告書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, 'クレーム報告書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T06';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T06' AND art.name = 'クレーム報告書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T06' AND art.name = 'クレーム報告書 承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T06' AND art.name = 'クレーム報告書 承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 4, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T06' AND art.name = 'クレーム報告書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 5, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T06' AND art.name = 'クレーム報告書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 企画外注向け注文書（50万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '企画外注向け注文書（50万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T08a';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T08a' AND art.name = '企画外注向け注文書（50万未満）承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

-- Route: 企画外注向け注文書（50万以上100万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '企画外注向け注文書（50万以上100万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T08b';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T08b' AND art.name = '企画外注向け注文書（50万以上100万未満）承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T08b' AND art.name = '企画外注向け注文書（50万以上100万未満）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

-- Route: 企画外注向け注文書（100万以上）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '企画外注向け注文書（100万以上）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T08c';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T08c' AND art.name = '企画外注向け注文書（100万以上）承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T08c' AND art.name = '企画外注向け注文書（100万以上）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T08c' AND art.name = '企画外注向け注文書（100万以上）承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T09a';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T09a' AND art.name = 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万未満）承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

-- Route: ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万以上100万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万以上100万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T09b';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T09b' AND art.name = 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万以上100万未満）承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T09b' AND art.name = 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（50万以上100万未満）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

-- Route: ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（100万以上）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（100万以上）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T09c';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画課長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T09c' AND art.name = 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（100万以上）承認ルート' AND e.email = 'hi-takahashi@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T09c' AND art.name = 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（100万以上）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T09c' AND art.name = 'ｸﾞﾚｰﾃﾞｨﾝｸﾞﾊﾟﾀｰﾝ作製依頼書（100万以上）承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 生地発注書（1000万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '生地発注書（1000万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T10a';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T10a' AND art.name = '生地発注書（1000万未満）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

-- Route: 生地発注書（1000万以上）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '生地発注書（1000万以上）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T10b';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T10b' AND art.name = '生地発注書（1000万以上）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T10b' AND art.name = '生地発注書（1000万以上）承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 付属発注書（1000万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '付属発注書（1000万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T11a';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T11a' AND art.name = '付属発注書（1000万未満）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

-- Route: 付属発注書（1000万以上）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '付属発注書（1000万以上）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T11b';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 1, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T11b' AND art.name = '付属発注書（1000万以上）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T11b' AND art.name = '付属発注書（1000万以上）承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 加工指図書（1000万未満）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '加工指図書（1000万未満）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T12a';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T12a' AND art.name = '加工指図書（1000万未満）承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 2, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T12a' AND art.name = '加工指図書（1000万未満）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '生産担当', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T12a' AND art.name = '加工指図書（1000万未満）承認ルート' AND e.email = 'y-mito@tsukamoto.co.jp';

-- Route: 加工指図書（1000～3000万）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '加工指図書（1000～3000万）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T12b';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T12b' AND art.name = '加工指図書（1000～3000万）承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T12b' AND art.name = '加工指図書（1000～3000万）承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T12b' AND art.name = '加工指図書（1000～3000万）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 4, '生産担当', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T12b' AND art.name = '加工指図書（1000～3000万）承認ルート' AND e.email = 'y-mito@tsukamoto.co.jp';

-- Route: 加工指図書（3000万以上）承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '加工指図書（3000万以上）承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T12c';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T12c' AND art.name = '加工指図書（3000万以上）承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T12c' AND art.name = '加工指図書（3000万以上）承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T12c' AND art.name = '加工指図書（3000万以上）承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 4, '企画生産部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T12c' AND art.name = '加工指図書（3000万以上）承認ルート' AND e.email = 'a-saito@tsukamoto.co.jp';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 5, '生産担当', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T12c' AND art.name = '加工指図書（3000万以上）承認ルート' AND e.email = 'y-mito@tsukamoto.co.jp';

-- Route: 請求書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '請求書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T13';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T13' AND art.name = '請求書 承認ルート' AND p.code = 'KACHO';

-- Route: 採寸申請書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '採寸申請書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T14';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '営業課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T14' AND art.name = '採寸申請書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '営業部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T14' AND art.name = '採寸申請書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T14' AND art.name = '採寸申請書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 海外出張申請書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '海外出張申請書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T15';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '所属課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T15' AND art.name = '海外出張申請書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '所属部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T15' AND art.name = '海外出張申請書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T15' AND art.name = '海外出張申請書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 海外出張報告書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '海外出張報告書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T16';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '所属課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T16' AND art.name = '海外出張報告書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '所属部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T16' AND art.name = '海外出張報告書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T16' AND art.name = '海外出張報告書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 国内出張報告書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '国内出張報告書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T17';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '所属課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T17' AND art.name = '国内出張報告書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '所属部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T17' AND art.name = '国内出張報告書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T17' AND art.name = '国内出張報告書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

-- Route: 有給休暇/半休申請書 承認ルート
INSERT INTO approval_route_templates (document_type_id, name, is_default, is_active)
SELECT dt.id, '有給休暇/半休申請書 承認ルート', true, true
FROM document_types dt WHERE dt.code = 'T18';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 1, '所属課長', 'position_in_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T18' AND art.name = '有給休暇/半休申請書 承認ルート' AND p.code = 'KACHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_position_id)
SELECT art.id, 2, '所属部長', 'position_in_parent_department', p.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN positions p
WHERE dt.code = 'T18' AND art.name = '有給休暇/半休申請書 承認ルート' AND p.code = 'BUCHO';

INSERT INTO approval_route_steps (route_template_id, step_order, name, assignee_type, assignee_employee_id)
SELECT art.id, 3, '事業部長', 'specific_employee', e.id
FROM approval_route_templates art
JOIN document_types dt ON art.document_type_id = dt.id
CROSS JOIN employees e
WHERE dt.code = 'T18' AND art.name = '有給休暇/半休申請書 承認ルート' AND e.email = 's-kuroki@tsukamoto.co.jp';

COMMIT;
